spring:
  config:
    import:
    - optional:configserver:http://localhost:8888
    
  application:
    name: limits-service
  
  cloud:
    config:
         
      profile: dev  
      enabled: true
eureka:
 client:  
 register-with-eureka: false
 fetch-registry: false